{{- $deployment := .Values.backend -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations: 
    released: {{ now }}    
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $deployment.role }}
  replicas: {{ $deployment.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $deployment.role }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
      - name: {{ $deployment.name }}
        image: {{ $deployment.image }}:{{ $deployment.imageTag }}
        env:
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:{{ $deployment.port }}"
        - name: MICRO_REGISTRY
          value: "mdns"
        - name: METRICS_PORT
          value: "{{ $deployment.port }}"
        - name: MICRO_SELECTOR
          value: "static"
        {{- range .Values.backend.env}}
        - name: {{.}}
          valueFrom:
            secretKeyRef:
              name: {{ $deploymentName }}-env
              key: {{.}}
        {{- end}}
        ports:
        - containerPort: {{$deployment.port}}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ $deployment.port }}
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: {{ $deployment.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 2
          periodSeconds: 5

